export const products = [
  {
    id: 1,
    name: "G502 HERO Wireless",
    category: "Gaming",
    price: 99.99,
    image: "/fire.png",
    description: "High Performance Gaming Mouse",
    brand: "Logitech",
  },
  {
    id: 2,
    name: "Pro Mechanical Keyboard",
    category: "Gaming",
    price: 149.99,
    image: "/G502.png",
    description: "RGB Mechanical Gaming Keyboard",
    brand: "Razer",
  },
  {
    id: 3,
    name: "Studio Headphones",
    category: "Professional",
    price: 199.99,
    image: "/Turbo.png",
    description: "Professional Studio Headphones",
    brand: "Audio-Technica",
  },
  {
    id: 4,
    name: "4K Gaming Monitor",
    category: "Gaming",
    price: 399.99,
    image: "/fire.png",
    description: "27-inch 4K HDR Gaming Monitor",
    brand: "ASUS",
  },
  {
    id: 5,
    name: "Ergonomic Office Chair",
    category: "Professional",
    price: 299.99,
    image: "/Turbo.png",
    description: "Comfortable Ergonomic Office Chair",
    brand: "Herman Miller",
  },
  {
    id: 6,
    name: "Wireless Gaming Headset",
    category: "Gaming",
    price: 129.99,
    image: "/G502.png",
    description: "Low-latency Wireless Gaming Headset",
    brand: "SteelSeries",
  },
];
